Update ua.json
Iternio-Planning-AB/abrp-translations pull request #653
Opened 2023-12-27 22:25 UTC by Apenflex

Hi. I made some changes in translation.

2023-12-29 10:03 UTC, knowbody commented
Hey, thanks a lot for your contribution! It seems like you removed quite a few translations. See the "files changed" tab. so we cannot accept this PR until that is fixed.

2023-12-29 10:04 UTC, knowbody requested changes

2023-12-29 10:04 UTC, knowbody commented on ua.json
> -  "delete_activity": "Видалити активності",
we need all of these back

2023-12-29 10:20 UTC, Apenflex commented
Ooo that's a problem I should check why all this lines have been gone. I
will fix and create new PR.

пт, 29 груд. 2023, 12:04 користувач Mateusz Zatorski <
***@***.***> пише:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In ua.json
> <https://github.com/Iternio-Planning-AB/abrp-translations/pull/653#discussion_r1438128663>
> :
>
> > -  "driving_settings_changed_description": "Щоб ці зміни відобразилися у вашому поточному плані, необхідно перепланувати маршрут.",
> -  "replan_needed": "Потрібне перепланування",
> -  "saved_destination_charge_at_location": "Зарядка в цьому місці",
> -  "saved_destination_charge_at_location_description": "Ця інформація є приватною та зберігається лише у вашому обліковому записі.",
> -  "open_app_settings": "Відкрити налаштування програми",
> -  "ignore_once": "Ігнорувати до наступного старту",
> -  "grant_automotive_permissions": "Перейдіть до налаштувань додатка і переконайтеся, що дозволи „Місцезнаходження“ та „Інформація про автомобіль“ надані.",
> -  "share_apple_link": "Відкрити в Apple Maps",
> -  "delete_all_activities": "Видалити збережені активності",
> -  "delete_all_activities_description": "Усі збережені активності, пов'язані з цим автомобілем, будуть видалені.",
> -  "delete_all_activities_dialog": "Ви впевнені, що хочете видалити всі активності, пов'язані з цим автомобілем?",
> -  "delete_activity": "Видалити активності",
>
> we need all of these back
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Iternio-Planning-AB/abrp-translations/pull/653#pullrequestreview-1798794229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXQLOQGCIGLZ52RNIRSITQDYL2ITZAVCNFSM6AAAAABBEZ6KESVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJYG44TIMRSHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-01-03 15:46 UTC, closed without merging

2024-01-03 15:46 UTC, knowbody commented
ok thank you, closing this one then.